jdk:
- oraclejdk8
language: java
install: true
cache:
  directories:
  - "$HOME/.m2/repository/"
before_script:
- export MVN_VER=3.3.9
- wget http://apache.claz.org/maven/maven-3/${MVN_VER}/binaries/apache-maven-${MVN_VER}-bin.tar.gz
- tar -zxvf apache-maven-${MVN_VER}-bin.tar.gz
- chmod +x apache-maven-${MVN_VER}/bin/mvn
- export PATH=$PWD/apache-maven-${MVN_VER}/bin:${PATH}
- mkdir -p ${HOME}/.m2/
- cp ./.travis/settings.xml ${HOME}/.m2/settings.xml
- pushd CloudySkySkin
- mvn -q install
- popd
- mvn -q install -DskipTests=true
script:
- if [ ${TRAVIS_BRANCH} = 'master' ]; then openssl aes-256-cbc -K $encrypted_05e49db982f1_key -iv $encrypted_05e49db982f1_iv -in .gpg.zip.enc -out .gpg.zip -d; fi;
- if [ ${TRAVIS_BRANCH} = 'master' ]; then unzip .gpg.zip -d ${HOME}/deploy/; fi
- pushd CloudySkySkin
- if [ ${TRAVIS_BRANCH} = 'master' ]; then mvn deploy -Dgpg.passphrase=${GPG_PASSPHRASE} -Dgpg.homedir=${HOME}/deploy/.gnupg/; else mvn test; fi;
- popd
- if [ ${TRAVIS_BRANCH} = 'master' ]; then mvn deploy -Dgpg.passphrase=${GPG_PASSPHRASE} -Dgpg.homedir=${HOME}/deploy/.gnupg/; else mvn test; fi;
- if [ ${TRAVIS_BRANCH} = 'master' ]; then mvn site -Psite-deploy; else mvn site; fi;
env:
  global:
